### PR TITLE
Add text domain to translate functions

### PR DESCRIPTION
**Pull request by perifer**
I needed this to translate "Författare" from just this plugin

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Please provide a swedish translation and open a new PR.

**Comment by perifer** [comment]
Do you mean that existing translations provided by this plugin will break when adding text domain as I did? Should I create knew .mo, .po and .pot files? My knowledge in Wordpress translations is somewhat limited...

The point with this PR is simply to add text domain which your other plugins seems to have.

**Comment by sebastianthulin** [comment]
Yes. Current solution rely on WordPress built-in translations-files. WordPress it self are not using any text-domain to make translations. 

Eg __("Author"); will be translated according to WordPress built-in translation. This plugin is intended to extend the UI of WordPress. Therefore we don´t need to add a text domain. Translation string would be added if needed. I thought this was the case here?

**Comment by perifer** [comment]
My usecase: I want to change Författare to Redaktör for the author picker (Höör wants this). When doing so also the Role "Författare" changed to Redaktör. Since there is already a Redaktör role we suddenly have two different roles with the exact same name. Confusing. By adding a text domain I was able to change Författare from this plugin, but not Författare from Wordpress.

I also noticed that you ship with translation files for your plugin, why do you do that if you say you rely on built in translations? Also, I think that Author _is_ still translated.

I'm using https://codex.wordpress.org/Plugin_API/Filter_Reference/gettext to change Författare to Redaktör.

**Comment by perifer** [comment]
So where are we with this? 

You ship translations (https://github.com/helsingborg-stad/better-post-UI/blob/master/languages/better-post-ui-sv_SE.po) already, is it anything you want me to do with this?

Maybe my usecase is better handled with a filter?

**Comment by sebastianthulin** [comment]
Yes. I believe a filter would be suitable for your need. This should be placed outside the __ or _e functions in order to be translatable. You may also create an boolean filter switching between "Author" and "Editor".

**Pull request closed without merging**
